/* Generated By:JavaCC: Do not edit this line. OrientSqlTreeConstants.java Version 5.0 */
package com.orientechnologies.orient.core.sql.parser;

public interface OrientSqlTreeConstants
{
  public int JJTRID = 0;
  public int JJTPARSE = 1;
  public int JJTIDENTIFIER = 2;
  public int JJTINTEGER = 3;
  public int JJTFLOATINGPOINT = 4;
  public int JJTNUMBER = 5;
  public int JJTSTATEMENT = 6;
  public int JJTQUERYSTATEMENT = 7;
  public int JJTSELECTWITHOUTTARGETSTATEMENT = 8;
  public int JJTSELECTSTATEMENT = 9;
  public int JJTTRAVERSESTATEMENT = 10;
  public int JJTMATCHSTATEMENT = 11;
  public int JJTDELETESTATEMENT = 12;
  public int JJTDELETEVERTEXSTATEMENT = 13;
  public int JJTDELETEEDGESTATEMENT = 14;
  public int JJTDELETEEDGEBYRIDSTATEMENT = 15;
  public int JJTDELETEEDGEFROMTOSTATEMENT = 16;
  public int JJTDELETEEDGETOSTATEMENT = 17;
  public int JJTDELETEEDGEVTOSTATEMENT = 18;
  public int JJTDELETEEDGEWHERESTATEMENT = 19;
  public int JJTUPDATEEDGESTATEMENT = 20;
  public int JJTUPDATESTATEMENT = 21;
  public int JJTUPDATEOPERATIONS = 22;
  public int JJTUPDATEITEM = 23;
  public int JJTUPDATEINCREMENTITEM = 24;
  public int JJTUPDATEREMOVEITEM = 25;
  public int JJTUPDATEPUTITEM = 26;
  public int JJTUPDATEADDITEM = 27;
  public int JJTUPDATEINSERTITEM = 28;
  public int JJTUPDATEDELETEITEM = 29;
  public int JJTINSERTSTATEMENT = 30;
  public int JJTINSERTBODY = 31;
  public int JJTCREATEVERTEXSTATEMENTEMPTYNOTARGET = 32;
  public int JJTCREATEVERTEXSTATEMENTEMPTY = 33;
  public int JJTCREATEVERTEXSTATEMENT = 34;
  public int JJTCREATEVERTEXSTATEMENTNOTARGET = 35;
  public int JJTCREATEEDGESTATEMENT = 36;
  public int JJTINPUTPARAMETER = 37;
  public int JJTPOSITIONALPARAMETER = 38;
  public int JJTNAMEDPARAMETER = 39;
  public int JJTPROJECTION = 40;
  public int JJTPROJECTIONITEM = 41;
  public int JJTARRAYSELECTOR = 42;
  public int JJTARRAYNUMBERSELECTOR = 43;
  public int JJTARRAYSINGLEVALUESSELECTOR = 44;
  public int JJTARRAYRANGESELECTOR = 45;
  public int JJTALIAS = 46;
  public int JJTRECORDATTRIBUTE = 47;
  public int JJTFUNCTIONCALL = 48;
  public int JJTMETHODCALL = 49;
  public int JJTLEVELZEROIDENTIFIER = 50;
  public int JJTSUFFIXIDENTIFIER = 51;
  public int JJTBASEIDENTIFIER = 52;
  public int JJTMODIFIER = 53;
  public int JJTEXPRESSION = 54;
  public int JJTMATHEXPRESSION = 55;
  public int JJTMULTEXPRESSION = 56;
  public int JJTFIRSTLEVELEXPRESSION = 57;
  public int JJTPARENTHESISEXPRESSION = 58;
  public int JJTBASEEXPRESSION = 59;
  public int JJTFROMCLAUSE = 60;
  public int JJTLETCLAUSE = 61;
  public int JJTLETITEM = 62;
  public int JJTFROMITEM = 63;
  public int JJTCLUSTER = 64;
  public int JJTCLUSTERLIST = 65;
  public int JJTMETADATAIDENTIFIER = 66;
  public int JJTINDEXIDENTIFIER = 67;
  public int JJTWHERECLAUSE = 68;
  public int JJTORBLOCK = 69;
  public int JJTANDBLOCK = 70;
  public int JJTNOTBLOCK = 71;
  public int JJTPARENTHESISBLOCK = 72;
  public int JJTCONDITIONBLOCK = 73;
  public int JJTCOMPAREOPERATOR = 74;
  public int JJTLTOPERATOR = 75;
  public int JJTGTOPERATOR = 76;
  public int JJTNEOPERATOR = 77;
  public int JJTNEQOPERATOR = 78;
  public int JJTGEOPERATOR = 79;
  public int JJTLEOPERATOR = 80;
  public int JJTLIKEOPERATOR = 81;
  public int JJTLUCENEOPERATOR = 82;
  public int JJTNEAROPERATOR = 83;
  public int JJTWITHINOPERATOR = 84;
  public int JJTSCANDOPERATOR = 85;
  public int JJTCONTAINSKEYOPERATOR = 86;
  public int JJTCONTAINSVALUEOPERATOR = 87;
  public int JJTEQUALSCOMPAREOPERATOR = 88;
  public int JJTBINARYCONDITION = 89;
  public int JJTCONTAINSVALUECONDITION = 90;
  public int JJTINSTANCEOFCONDITION = 91;
  public int JJTINDEXMATCHCONDITION = 92;
  public int JJTBETWEENCONDITION = 93;
  public int JJTISNULLCONDITION = 94;
  public int JJTISNOTNULLCONDITION = 95;
  public int JJTISDEFINEDCONDITION = 96;
  public int JJTISNOTDEFINEDCONDITION = 97;
  public int JJTCONTAINSCONDITION = 98;
  public int JJTINOPERATOR = 99;
  public int JJTINCONDITION = 100;
  public int JJTNOTINCONDITION = 101;
  public int JJTCONTAINSALLCONDITION = 102;
  public int JJTCONTAINSTEXTCONDITION = 103;
  public int JJTMATCHESCONDITION = 104;
  public int JJTORDERBY = 105;
  public int JJTGROUPBY = 106;
  public int JJTUNWIND = 107;
  public int JJTLIMIT = 108;
  public int JJTSKIP = 109;
  public int JJTBATCH = 110;
  public int JJTTIMEOUT = 111;
  public int JJTWAIT = 112;
  public int JJTRETRY = 113;
  public int JJTCOLLECTION = 114;
  public int JJTFETCHPLAN = 115;
  public int JJTFETCHPLANITEM = 116;
  public int JJTTRAVERSEPROJECTIONITEM = 117;
  public int JJTJSON = 118;
  public int JJTMATCHEXPRESSION = 119;
  public int JJTMATCHPATHITEM = 120;
  public int JJTMATCHPATHITEMFIRST = 121;
  public int JJTMULTIMATCHPATHITEM = 122;
  public int JJTMULTIMATCHPATHITEMARROWS = 123;
  public int JJTMATCHFILTER = 124;
  public int JJTMATCHFILTERITEM = 125;
  public int JJTOUTPATHITEM = 126;
  public int JJTINPATHITEM = 127;
  public int JJTBOTHPATHITEM = 128;
  public int JJTOUTPATHITEMOPT = 129;
  public int JJTINPATHITEMOPT = 130;
  public int JJTBOTHPATHITEMOPT = 131;
  public int JJTPROFILESTORAGESTATEMENT = 132;


  public String[] jjtNodeName = {
    "Rid",
    "parse",
    "Identifier",
    "Integer",
    "FloatingPoint",
    "Number",
    "Statement",
    "QueryStatement",
    "SelectWithoutTargetStatement",
    "SelectStatement",
    "TraverseStatement",
    "MatchStatement",
    "DeleteStatement",
    "DeleteVertexStatement",
    "DeleteEdgeStatement",
    "DeleteEdgeByRidStatement",
    "DeleteEdgeFromToStatement",
    "DeleteEdgeToStatement",
    "DeleteEdgeVToStatement",
    "DeleteEdgeWhereStatement",
    "UpdateEdgeStatement",
    "UpdateStatement",
    "UpdateOperations",
    "UpdateItem",
    "UpdateIncrementItem",
    "UpdateRemoveItem",
    "UpdatePutItem",
    "UpdateAddItem",
    "UpdateInsertItem",
    "UpdateDeleteItem",
    "InsertStatement",
    "InsertBody",
    "CreateVertexStatementEmptyNoTarget",
    "CreateVertexStatementEmpty",
    "CreateVertexStatement",
    "CreateVertexStatementNoTarget",
    "CreateEdgeStatement",
    "InputParameter",
    "PositionalParameter",
    "NamedParameter",
    "Projection",
    "ProjectionItem",
    "ArraySelector",
    "ArrayNumberSelector",
    "ArraySingleValuesSelector",
    "ArrayRangeSelector",
    "Alias",
    "RecordAttribute",
    "FunctionCall",
    "MethodCall",
    "LevelZeroIdentifier",
    "SuffixIdentifier",
    "BaseIdentifier",
    "Modifier",
    "Expression",
    "MathExpression",
    "MultExpression",
    "FirstLevelExpression",
    "ParenthesisExpression",
    "BaseExpression",
    "FromClause",
    "LetClause",
    "LetItem",
    "FromItem",
    "Cluster",
    "ClusterList",
    "MetadataIdentifier",
    "IndexIdentifier",
    "WhereClause",
    "OrBlock",
    "AndBlock",
    "NotBlock",
    "ParenthesisBlock",
    "ConditionBlock",
    "CompareOperator",
    "LtOperator",
    "GtOperator",
    "NeOperator",
    "NeqOperator",
    "GeOperator",
    "LeOperator",
    "LikeOperator",
    "LuceneOperator",
    "NearOperator",
    "WithinOperator",
    "ScAndOperator",
    "ContainsKeyOperator",
    "ContainsValueOperator",
    "EqualsCompareOperator",
    "BinaryCondition",
    "ContainsValueCondition",
    "InstanceofCondition",
    "IndexMatchCondition",
    "BetweenCondition",
    "IsNullCondition",
    "IsNotNullCondition",
    "IsDefinedCondition",
    "IsNotDefinedCondition",
    "ContainsCondition",
    "InOperator",
    "InCondition",
    "NotInCondition",
    "ContainsAllCondition",
    "ContainsTextCondition",
    "MatchesCondition",
    "OrderBy",
    "GroupBy",
    "Unwind",
    "Limit",
    "Skip",
    "Batch",
    "Timeout",
    "Wait",
    "Retry",
    "Collection",
    "FetchPlan",
    "FetchPlanItem",
    "TraverseProjectionItem",
    "Json",
    "MatchExpression",
    "MatchPathItem",
    "MatchPathItemFirst",
    "MultiMatchPathItem",
    "MultiMatchPathItemArrows",
    "MatchFilter",
    "MatchFilterItem",
    "OutPathItem",
    "InPathItem",
    "BothPathItem",
    "OutPathItemOpt",
    "InPathItemOpt",
    "BothPathItemOpt",
    "ProfileStorageStatement",
  };
}
/* JavaCC - OriginalChecksum=ee3ef372eb56c1597db3a326b15ed97b (do not edit this line) */
