/* Generated By:JJTree: Do not edit this line. OUpdateDeleteItem.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.orientechnologies.orient.core.sql.parser;

import java.util.Map;

public
class OUpdateDeleteItem extends SimpleNode {
  
  OIdentifier field;
  int index;
  
  public OUpdateDeleteItem(int id) {
    super(id);
  }

  public OUpdateDeleteItem(OrientSql p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(OrientSqlVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    builder.append("FROM ");
    field.toString(params, builder);
    builder.append(" AT ");
    builder.append(index);
  }
}
/* JavaCC - OriginalChecksum=4c538c493051ee5e967feda61f61f5cc (do not edit this line) */
